// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    DateCalendar: typeof import("./src/components/DateCalendar.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCollapse: typeof import("element-plus/es")["ElCollapse"];
    ElCollapseItem: typeof import("element-plus/es")["ElCollapseItem"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElInputNumber: typeof import("element-plus/es")["ElInputNumber"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElPopconfirm: typeof import("element-plus/es")["ElPopconfirm"];
    ElPopover: typeof import("element-plus/es")["ElPopover"];
    ElProgress: typeof import("element-plus/es")["ElProgress"];
    ElRadio: typeof import("element-plus/es")["ElRadio"];
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSlider: typeof import("element-plus/es")["ElSlider"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    Graph: typeof import("./src/components/Graph.vue")["default"];
    Icon: typeof import("./src/components/Icon.vue")["default"];
    Loading: typeof import("element-plus/es")["ElLoadingDirective"];
    Radio: typeof import("./src/components/Radio.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Selector: typeof import("./src/components/Selector.vue")["default"];
    SelectSingle: typeof import("./src/components/SelectSingle.vue")["default"];
    TimePicker: typeof import("./src/components/TimePicker.vue")["default"];
  }
}

export {};
