export const data = [
  [{ id: "Chaos" }],
  [{ id: "Gaea", parents: ["Chaos"] }, { id: "Uranus" }],
  [
    { id: "Oceanus", parents: ["Gaea", "Uranus"] },
    { id: "Thethys", parents: ["Gaea", "Uranus"] },
    { id: "Pontus" },
    { id: "Rhea", parents: ["Gaea", "Uranus"] },
    { id: "Cronus", parents: ["Gaea", "Uranus"] },
    { id: "Coeus", parents: ["Gaea", "Uranus"] },
    { id: "Phoebe", parents: ["Gaea", "Uranus"] },
    { id: "Crius", parents: ["Gaea", "Uranus"] },
    { id: "Hyperion", parents: ["Gaea", "Uranus"] },
    { id: "Iapetus", parents: ["Gaea", "Uranus"] },
    { id: "Thea", parents: ["Gaea", "Uranus"] },
    { id: "Themis", parents: ["Gaea", "Uranus"] },
    { id: "Mnemosyne", parents: ["Gaea", "Uranus"] },
  ],
  [
    { id: "Doris", parents: ["Oceanus", "Thethys"] },
    { id: "Neures", parents: ["Pontus", "Gaea"] },
    { id: "Dionne" },
    { id: "Demeter", parents: ["Rhea", "Cronus"] },
    { id: "Hades", parents: ["Rhea", "Cronus"] },
    { id: "Hera", parents: ["Rhea", "Cronus"] },
    { id: "Alcmene" },
    { id: "Zeus", parents: ["Rhea", "Cronus"] },
    { id: "Eris" },
    { id: "Leto", parents: ["Coeus", "Phoebe"] },
    { id: "Amphitrite" },
    { id: "Medusa" },
    { id: "Poseidon", parents: ["Rhea", "Cronus"] },
    { id: "Hestia", parents: ["Rhea", "Cronus"] },
  ],
  [
    { id: "Thetis", parents: ["Doris", "Neures"] },
    { id: "Peleus" },
    { id: "Anchises" },
    { id: "Adonis" },
    { id: "Aphrodite", parents: ["Zeus", "Dionne"] },
    { id: "Persephone", parents: ["Zeus", "Demeter"] },
    { id: "Ares", parents: ["Zeus", "Hera"] },
    { id: "Hephaestus", parents: ["Zeus", "Hera"] },
    { id: "Hebe", parents: ["Zeus", "Hera"] },
    { id: "Hercules", parents: ["Zeus", "Alcmene"] },
    { id: "Megara" },
    { id: "Deianira" },
    { id: "Eileithya", parents: ["Zeus", "Hera"] },
    { id: "Ate", parents: ["Zeus", "Eris"] },
    { id: "Leda" },
    { id: "Athena", parents: ["Zeus"] },
    { id: "Apollo", parents: ["Zeus", "Leto"] },
    { id: "Artemis", parents: ["Zeus", "Leto"] },
    { id: "Triton", parents: ["Poseidon", "Amphitrite"] },
    { id: "Pegasus", parents: ["Poseidon", "Medusa"] },
    { id: "Orion", parents: ["Poseidon"] },
    { id: "Polyphemus", parents: ["Poseidon"] },
  ],
  [
    { id: "Deidamia" },
    { id: "Achilles", parents: ["Peleus", "Thetis"] },
    { id: "Creusa" },
    { id: "Aeneas", parents: ["Anchises", "Aphrodite"] },
    { id: "Lavinia" },
    { id: "Eros", parents: ["Hephaestus", "Aphrodite"] },
    { id: "Helen", parents: ["Leda", "Zeus"] },
    { id: "Menelaus" },
    { id: "Polydueces", parents: ["Leda", "Zeus"] },
  ],
  [
    { id: "Andromache" },
    { id: "Neoptolemus", parents: ["Deidamia", "Achilles"] },
    { id: "Aeneas(2)", parents: ["Creusa", "Aeneas"] },
    { id: "Pompilius", parents: ["Creusa", "Aeneas"] },
    { id: "Iulus", parents: ["Lavinia", "Aeneas"] },
    { id: "Hermione", parents: ["Helen", "Menelaus"] },
  ],
];
